@echo off
:: SetGitInfo.cmd — writes the current git hash into GitInfo.cs before each build.
:: called by PreBuildEvent in PZManager.csproj.
:: uses plain cmd/batch — no PowerShell, no execution policy nonsense.

set VERSION=%2
set OUTFILE=%1GitInfo.cs

:: try to get the short hash from git
for /f "tokens=*" %%i in ('git rev-parse --short HEAD 2^>nul') do set HASH=%%i

:: if git failed or we're not in a repo, fall back gracefully
if "%HASH%"=="" set HASH=unknown

:: write the file — echo each line, redirect first then append
(
echo // auto-generated by SetGitInfo.cmd before each build — do not edit by hand.
echo // changes to this file will be overwritten on the next build.
echo namespace PZManager
echo {
echo     internal static class GitInfo
echo     {
echo         public const string Hash        = "%HASH%";
echo         public const string Version     = "%VERSION%";
echo         public const string FullVersion = "%VERSION%+%HASH%";
echo     }
echo }
) > "%OUTFILE%"

echo SetGitInfo: wrote GitInfo.cs (hash=%HASH%, version=%VERSION%)
