# SetGitInfo.ps1
# runs before every build and writes the current git hash into GitInfo.cs.
# called by the PreBuildEvent in PZManager.csproj.
# safe to commit — it's just a script, not generated output.

param(
    [string]$ProjectDir,
    [string]$Version = "1.0.0"
)

# get the short hash — if git fails for any reason, use "unknown"
try {
    $hash = (git rev-parse --short HEAD 2>$null).Trim()
    if ([string]::IsNullOrWhiteSpace($hash)) { $hash = "unknown" }
} catch {
    $hash = "unknown"
}

$content = @"
// auto-generated by SetGitInfo.ps1 before each build — do not edit by hand.
// changes to this file will be overwritten on the next build.
// if you see "unknown" in the About page, make sure git is on your PATH and you have at least one commit.
namespace PZManager
{
    internal static class GitInfo
    {
        public const string Hash        = "$hash";
        public const string Version     = "$Version";
        public const string FullVersion = "$Version+$hash";
    }
}
"@

$output_path = Join-Path $ProjectDir "GitInfo.cs"

# only write if content changed — avoids unnecessary recompiles
$existing = if (Test-Path $output_path) { Get-Content $output_path -Raw } else { "" }
if ($existing -ne $content) {
    Set-Content -Path $output_path -Value $content -Encoding UTF8 -NoNewline:$false
    Write-Host "SetGitInfo: wrote $output_path (hash=$hash)"
} else {
    Write-Host "SetGitInfo: no change (hash=$hash)"
}
